name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - uses: actions/checkout@v4

      # 2. Validar el composer.json y composer.lock
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      # 3. Cachear las dependencias de Composer para acelerar el flujo
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # 4. Instalar dependencias con Composer
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      # 5. Ejecutar pruebas con PHPUnit
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit tests/


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
